theme: minima
title: A little lite AI
email: timm@ieee.org
description: >- # this means to ignore newlines until "baseurl:"
  Sure, you can write your own AI. Easy!
url: "http://github.io/timm/lite" # the base hostname & protocol for your site, e.g. http://example.com
